---
version: '3'

tasks:
  default:
    cmds:
      - task: format
      - task: lint_and_test

  lint_and_test:
    deps: [lint, test]

  format:
    cmds:
      - uv run ruff format --respect-gitignore
      - uv run ruff check --fix
      - task: format_node

  format_node:
    deps: [format_biome, format_markdownlint, format_toml]

  format_biome:
    cmds:
      - pnpm exec biome check --write

  format_markdownlint:
    cmds:
      - pnpm exec markdownlint-cli2 --fix

  format_toml:
    cmds:
      - taplo format *.toml

  lint:
    deps: [lint_yaml, lint_ruff_format, lint_ruff_check, lint_node, lint_typos]

  lint_node:
    deps: [lint_biome, lint_md, lint_pyright, lint_toml]

  lint_biome:
    cmds:
      - pnpm exec biome check

  lint_md:
    cmds:
      - pnpm exec markdownlint-cli2

  lint_pyright:
    cmds:
      - pnpm exec pyright

  lint_toml:
    cmds:
      - taplo format --check *.toml

  lint_yaml:
    cmds:
      - >-
        find . \( -name node_modules -o -name .venv \) \
         -prune -o -type f \( -name "*.yaml" -o -name "*.yml" \) -print \
        | xargs uv run yamllint

  lint_ruff_format:
    cmds:
      - uv run ruff format --respect-gitignore --check

  lint_ruff_check:
    cmds:
      - uv run ruff check --respect-gitignore

  lint_typos:
    cmds:
      - typos -V && typos

  test:
    cmds:
      - ':'
