"""Data models for llama-swap configuration generation."""

from pathlib import Path
from typing import Any

import yaml
from pydantic import BaseModel, ConfigDict, Field


class CapabilitiesConfig(BaseModel):
    model_config = ConfigDict(populate_by_name=True)

    in_: list[str] | None = Field(default=None, alias="in", description="Input modalities understood by the model")
    out: list[str] | None = Field(default=None, description="Output modalities generated by the model")
    tools: bool | None = Field(default=None, description="Whether the model supports function calling")
    reranker: bool | None = Field(default=None, description="Whether the model supports the /v1/rerank endpoint")
    context: int | None = Field(default=None, description="Maximum token context length supported by the model")

    def to_yaml_dict(self) -> dict[str, Any]:
        return self.model_dump(by_alias=True, exclude_none=True)


class MmprojConfig(BaseModel):
    enabled: bool = Field(default=True)
    auto_attach: bool = Field(default=True)
    arg: str = Field(default="--mmproj")
    overrides: dict[str, Path] = Field(default_factory=dict)
    generate_no_mmproj_variant: bool = Field(default=False)
    no_mmproj_suffix: str = Field(default=" (no mmproj)")


class Config(BaseModel):
    model_config = ConfigDict(extra="allow")

    models: list[Path] = Field(description="List of model directory paths")
    macros: dict[str, str] = Field(default_factory=dict)
    model_patterns: dict[str, Any] = Field(default_factory=dict)
    variants: list[dict[str, Any]] = Field(default_factory=list)
    variant_presets: dict[str, Any] = Field(default_factory=dict)
    mmproj: MmprojConfig = Field(default_factory=MmprojConfig)
    default_ttl: int = Field(default=300)
    vram_estimation: bool = Field(default=False)
    read_gguf_metadata: bool = Field(
        default=False,
        description="Read GGUF chat_template/architecture headers to auto-derive capabilities "
        "(tools, reasoning_supported) even when vram_estimation is disabled.",
    )
    path_prefix_map: dict[str, str] = Field(
        default_factory=dict,
        description="Rewrites host-side model paths (as scanned under `models:`) to the path seen by the "
        "runtime (e.g. inside a container), applied to both the generated cmd's -m argument and any "
        "--llama-bin fit-params invocation.",
    )


class VariantPresetItem(BaseModel):
    suffix: str
    macro: str


class ModelPatternConfig(BaseModel):
    model_config = ConfigDict(extra="allow")

    macro: str
    emit_base: bool = Field(default=True)
    variants: list[str] = Field(default_factory=list)
    mmproj: str | None = Field(default=None)
    capabilities: CapabilitiesConfig | None = Field(default=None)


class MacroConfig(BaseModel):
    macros: dict[str, str] = Field(default_factory=dict)
    model_patterns: dict[str, ModelPatternConfig] = Field(default_factory=dict)
    variants: list[dict[str, Any]] = Field(default_factory=list)
    variant_presets: dict[str, list[VariantPresetItem]] = Field(default_factory=dict)


class Settings(BaseModel):
    models_dirs: list[Path]
    default_ttl: int = Field(default=300)
    config_file: Path
    vram_estimation: bool = Field(default=False)
    read_gguf_metadata: bool = Field(default=False)
    path_prefix_map: dict[str, str] = Field(default_factory=dict)
    llama_bin: list[str] | None = Field(default=None)


class MultilineLiteral(str):
    """Custom YAML string class to force literal block scalar style"""

    pass


def multiline_literal_representer(dumper: yaml.Dumper, data: MultilineLiteral) -> yaml.ScalarNode:
    return dumper.represent_scalar("tag:yaml.org,2002:str", data, style="|")


yaml.add_representer(MultilineLiteral, multiline_literal_representer)


class YamlModelConfig(BaseModel):
    ttl: int = Field(description="Time to live for the model in seconds")
    cmd: MultilineLiteral = Field(description="Command to run the model")
    name: str = Field(description="Display name for the model")
    capabilities: CapabilitiesConfig | None = Field(
        default=None, description="Model capabilities such as context length"
    )
    metadata: dict[str, Any] | None = Field(default=None, description="Provider metadata exposed by llama-swap")

    model_config = {"arbitrary_types_allowed": True}


class YamlConfig(BaseModel):
    healthCheckTimeout: int = Field(description="Health check timeout in seconds")
    logLevel: str = Field(description="Log level")
    startPort: int = Field(description="Starting port number")
    models: dict[str, YamlModelConfig] = Field(default_factory=dict, description="Model configurations")
